#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-eks-service
spec:
  type: LoadBalancer
  selector:
    app: flask-eks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
